name: Daily PR Review Reminder

on:
  schedule:
  
    - cron: "0 15 * * *"
  workflow_dispatch: # lets you run it manually

permissions:
  contents: read
  issues: write

jobs:
  create-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
    
      - name: Create reminder issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Daily Reminder: Review Marselena's PRs"
          content-filepath: .github/reminders/marselena-prs.md
          labels: "reminder, automated"
